### PR TITLE
fix cargo doc lint issues

### LINKED ISSUE #110: Run rustdoc in CI
Running `cargo doc` does currently show some warnings about broken links, but this isn't picked up by CI. We should add a job that runs `cargo doc` with the `RUSTDOCFLAGS` environment variable set to `-Dwarnings` to fail on doc issues.

### PR DESCRIPTION
**Pull request by almindor**
Simple docs lint fixes PR + adds docs build check to CI. Fixes #110

### CODE REVIEW

File: mipidsi/src/lib.rs [hunk 1]
```diff
@@ -250,7 +250,7 @@ where
     /// The combined height of the fixed area must not larger than the
     /// height of the framebuffer height in the default orientation.
     ///
-    /// After the scrolling region is defined the [`set_scroll_offset`] can be
+    /// After the scrolling region is defined the [Self::set_vertical_scroll_offset] can be
```
Comment (rfuest) [inline mipidsi/src/lib.rs:253]: It's common practice to not include `Self` when referring to methods in the same type, which makes the docs easier to read. Method names should also be inside a code span:
```suggestion
    /// After the scrolling region is defined the [`set_vertical_scroll_offset`](Self::set_vertical_scroll_offset) can be
```

Other parts of the docs also don't follow this convention. I think we should go through the docs an adjust all links to use the same style. Do you want to include this change in this PR? Or would you like me to take a look at this, after this is merged?

File: mipidsi/src/lib.rs [hunk 2]
```diff
@@ -277,7 +277,7 @@ where
     /// Setting the vertical scroll offset shifts the vertical scroll region
     /// upwards by `offset` pixels.
     ///
-    /// Use [`set_vertical_scroll_region`] to setup the scroll region, before
+    /// Use [Self::set_vertical_scroll_region] to setup the scroll region, before
```
Comment (rfuest) [inline mipidsi/src/lib.rs:280]:
```suggestion
    /// Use [`set_vertical_scroll_region`](Self::set_vertical_scroll_region) to setup the scroll region, before
```

**Review by rfuest — CHANGES_REQUESTED** [review]
A small stylistic nit, but it looks good otherwise. Having the docs checked in CI should improve the quality of our docs.
