### PR TITLE
Fix size and orientation issues

### LINKED ISSUE #7: screen orientations are hardcoded
Some screens require different madctl 0x26 settings, and e.g. will appear reversed without.

For a possible solution see: https://github.com/yuri91/ili9341-rs/commit/8a4aee95c2934cd6aaac4b243ab8bda24d0b7475

### LINKED ISSUE #8: screen size hardcoded and does not change with orientation
Screen size is hard-coded and should vary depending on the orientation settings.

### PR DESCRIPTION
**Pull request by brianmay**
Fixes #7
Fixes #8

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -64,8 +64,6 @@ where
 pub enum Orientation {
     Portrait = 0b0000_0000,         // no inverting
     Landscape = 0b0110_0000,        // invert column and page/column order
```
Comment (brianmay) [inline src/lib.rs:66]: I would also be setting this to just `0b0010_0000` as the 2nd bit can be inverted if required.

**Comment by almindor** [comment]
Sorry about the delay, I need to get my setup in working order again after losing an mcu to a short. I should be able to test these in a week or so.

**Comment by brianmay** [comment]
Rebased to latest master.

File: src/graphics.rs [hunk 2]
```diff
@@ -95,18 +95,16 @@ where
     }
 
     fn clear(&mut self, color: Self::Color) -> Result<(), Self::Error>
-    where
-        Self: Sized,
```
Comment (brianmay) [inline src/graphics.rs:99]: I don't remember making this change. I don't see any good reason for the including these lines, so I left it in.

File: src/lib.rs (hunk 1 above)
Comment (almindor) [reply src/lib.rs:68]: I'm wondering if it wouldn't be more straightforward to have a flat enum for all the possible combinations rather than the "invert x/y".

File: src/graphics.rs (hunk 2 above)
Comment (almindor) [reply src/graphics.rs:99]: I think Self: Sized is implied either way?

File: src/graphics.rs [hunk 3]
```diff
@@ -67,10 +67,10 @@ where
     }
 
     fn fill_solid(&mut self, area: &Rectangle, color: Self::Color) -> Result<(), Self::Error> {
-        let fb_size = self.model.framebuffer_size();
```
Comment (almindor) [inline src/graphics.rs:70]: I'm still conflicted about this. Framebuffer_size is supposed to be "the whole pixel memory" which in case of clear is what we want AFAICS.

File: src/graphics.rs (hunk 2 above)
Comment (brianmay) [reply src/graphics.rs:99]: Yes, I think it is.

File: src/graphics.rs (hunk 3 above)
Comment (brianmay) [reply src/graphics.rs:70]: Clear doesn't use `fill_solid`. At least not with this version. So nothing here is going to affect the clear function.

However I do have an alternative approach. Will add another commit, see if you like that any better.

File: src/lib.rs (hunk 1 above)
Comment (brianmay) [reply src/lib.rs:68]: That is going to be a lot of combinations. Basically there are 3 bits, so 2*2*2 = 8 combinations. Think it might be more confusing, not less confusing.

Although personally, wondering if it would be better just to have:

```
pub enum Orientation {
    Portrait,
    Landscape,
}
```

And have the `set_orientation` function map that to the correct value.

File: src/graphics.rs (hunk 3 above)
Comment (brianmay) [reply src/graphics.rs:70]: I added a `framebuffer_size` function and use that now, hopefully this will address your concern here.

Comment (brianmay) [reply src/graphics.rs:70]: Having said that, there is still the problem that both "whole pixel memory" and "displayable area" both need to start at 0,0. I don't think the concept is very usable as is.

File: src/graphics.rs [hunk 4]
```diff
@@ -8,6 +8,19 @@ use crate::models::Model;
 use crate::{Display, Error, Orientation};
 use display_interface::WriteOnlyDataCommand;
 
+fn framebuffer_size<DI, RST, M>(display: &Display<DI, RST, M>) -> (u16, u16)
```
Comment (brianmay) [inline src/graphics.rs:11]: Thought about making this return a `Size` object. That would clarify which one is width vs height. But Size objects use u32 dimensions. And `pixel_count` below uses `usize` dimensions. And `usize::from` works fine for u16, but fails for u32. So I stuck with the above for now.

File: src/lib.rs [hunk 5]
```diff
@@ -242,6 +251,19 @@ where
             .map_err(|_| Error::DisplayError)
     }
 
+    fn framebuffer_size(&self) -> (u16, u16)
```
Comment (brianmay) [inline src/lib.rs:254]: Thought about making this return a `Size` object. That would clarify which one is width vs height. But Size objects use u32 dimensions. And `pixel_count` in `graphics.rs` uses `usize` dimensions. And `usize::from` works fine for u16, but fails for u32. So I stuck with the above for now.

File: src/lib.rs (hunk 1 above)
Comment (brianmay) [reply src/lib.rs]: Also worth noting, yes, we really do need to support all of 8 combinations. Depending on how the display is mounted and if the hardware reverses the image or not.

Comment (almindor) [reply src/lib.rs]: Hmm the main issue I have with this is that splitting the orientation enum and the "revert" values seem confusing. We could do something like
```rust
pub enum Orientation {
    Portrait(bool, bool), // x/y invert
    Landscape(bool, bool), // x/y invert
}
```

Or possibly introduce a new sub-enum for "inversion" and use that as the inner value.

**Comment by almindor** [comment]
@brianmay what is instead of having "two world" (model vs display/lib) we unify the `framebuffer_size` in the model by either enforcing the orientation knowledge in the model, or by making it into `fn frabebuffer_size(&self, orientation: Orientation)` (provided `Orientation` has all the required info as I'd like).

This way we can keep a single source of size info. Same can be done for `display_size` then.

File: src/lib.rs (hunk 1 above)
Comment (brianmay) [reply src/lib.rs]: Hmmm. Not sure I can see how this could be less confusing. Also most of the code only needs to know if it is Portrait/Landscape. If the display is inverted or not makes no difference. i.e. the invert parameters are only really needed to configure the MADCTL register and don't matter afterward. In fact the invert parameters have no real meaning outside the MADCTL because there is no real way to know what the hardware is doing with them. Maybe setting invert_x will invert the display, or maybe setting invert_x will restore the display.

Maybe that is the problem though. We use the `set_orientation` to set parameters that are not orientation. You wouldn't set the RGB/BGR value here. But the problem being it is interconnected. When setting orientation you typically will (always) have to adjust the invert values at the same time. Which is why we do it in the `set_orientation` call.

**Comment by brianmay** [comment]
> @brianmay what is instead of having "two world" (model vs display/lib) we unify the `framebuffer_size` in the model by either enforcing the orientation knowledge in the model, or by making it into `fn frabebuffer_size(&self, orientation: Orientation)` (provided `Orientation` has all the required info as I'd like).
> 
> This way we can keep a single source of size info. Same can be done for `display_size` then.

I would be happy with both of these approaches. At present the model has no state information, the display is the authoritative source for all information. We probably should keep this unless we have a good reason to change it (e.g. if RGB/BGR config requires it). If so, then the later option would suffice. Also note that we only need to know the Portrait/Landscape stuff, we don't need to know bout the invert stuff here.

File: src/lib.rs (hunk 5 above)
Comment (almindor) [reply src/lib.rs:254]: `u32 as usize` should be safe in 32bit+ machines of course there are very special edge cases (there's a whole thing with ptrsize vs usize in rust). for our purposes and expected display sizes I think it's 100% safe to just case that way.

**Review by almindor — APPROVED** [review]
I'm going to merge this and then follow up with a PR to clarify with the orientation being pushed into `Model::*_size()` functions instead.
